# Local Verilog Agent Configuration

# Core Settings
# Prompt defines the default prompt to use when running the agent
# Instructions provide specific functionality requirements or other guidance to agent
prompt: "Design a 8-bit register with active low asynchronous reset" 

instructions: |
  Use Verilog-2001 standard.
 
# LLM Settings
llm:
  # Change this to "ollama" or "huggingface" to switch providers
  provider: "huggingface" 

  ollama:
    model: "gpt-oss:20b"

  huggingface:
    model: "Qwen/Qwen2.5-Coder-32B-Instruct"
    api_key: "" 
    api_url: "https://router.huggingface.co/v1/chat/completions" # Router Endpoint

# Simulation Settings
max_retries: 30
workspace_dir: "build"

# Output Settings
designs_dir: "designs"
save_on_success: true
show_diffs: true
